# Mission for Demo (submerge and forward)
waypoints:
  - name: "Submerge"
    cmd: {x: 0.0, y: 0.0, z: -0.5, yaw: 0.0}
    duration: 2000 # ms
  
  # - name: "Wait for Start Signal"
  #   type: "wait_for_trigger" # Special action

  - name: "Wait 5 Seconds"
    type: "delay"
    value: 5000 # Wait for 5 seconds

  - name: "Forward through Gate"
    cmd: {x: 1.0, y: 0.0, z: 0.0, yaw: 0.0}
    duration: 5000 # Move forward for 5 seconds