# Mission for Demo Zigzag
waypoints:
  - name: "Submerge"
    cmd: {x: 0.0, y: 0.0, z: -0.5, yaw: 0.0}
    duration: 2000 # ms
  
  # - name: "Wait for Start Signal"
  #   type: "wait_for_trigger" # Special action

  - name: "Wait 5 Seconds"
    type: "delay"
    value: 5000 # Wait for 5 seconds

  - name: "Move Left Diagonal"
    cmd: {x: 0.25, y: 0.25, z: 0.0, yaw: 0.0}
    duration: 3000 # Move forward-left for 2 seconds

  - name: "Move Right Diagonal"
    cmd: {x: 0.5, y: -0.5, z: 0.0, yaw: 0.0}
    duration: 3000 # Move right for 3 seconds

  - name: "Move Left Diagonal"
    cmd: {x: 0.25, y: 0.25, z: 0.0, yaw: 0.0}
    duration: 3000 # Move forward-left for 3 seconds

  - name: "Forward through Gate"
    cmd: {x: 1.0, y: 0.0, z: 0.0, yaw: 0.0}
    duration: 5000 # Move forward for 5 seconds